Added login/logout functionality. Made changes to the Course and Temp…
j2kan/ta-works pull request #2
Opened 2017-07-11 03:45 UTC by lauradobson

…Course model to account for no null values in all fields except instructor name and instructor email.

2017-07-11 05:05 UTC, j2kan requested changes
great lot of good features.

notice that 
style="vertical-align:top; float: right">Home</button>
was used in multiple places.

The DRY principal is a good reason why we should move these to the static/css/ folder.

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/models.py
> +    course_subject = models.CharField(null=True, max_length=255)
Can you move all the null=True to come after max_length just to be consistent with the rest of the models?

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/models.py
> +    course_name = models.CharField(null=True, max_length=255)
same as above.

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
add css to static/taform/css/style.css

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
check spacing around this block

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
add {% csrf_token %}

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +    <div>
remove indent

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +    </div>
remove indent

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +    <font color="red">{{error}}</font>
add css to static/taform/css/style.css

fix spacing int his area

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_success.html
> +        </form>
fix indent

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_success.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
add css to static/taform/css/style.css

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/course_success.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
add cross site forgery token

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +    <html>
remove indent, don't need to indent at start of file

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +        <form>
remove indent, 
add css to static/taform/css/style.css
add CSRF.token

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +        <h1><legend>TA Application Home Page</legend></h1>
too much indent

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/test.html
> +    <form>
remove indent

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/test.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
add css to static/taform/css/style.css

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/urls.py
> +    url(r'application.html', views.apply, name='application'),
we can remove this and change line 30 from home.html from
<td class="tg-yw4l"><a href="application.html">TA Application</a></td>
to
<td class="tg-yw4l"><a href="/">TA Application</a></td>

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/urls.py
> +    url(r'^logout.html', views.logout, name='logout'),
remove ^ on line 13 and 14, consistent with the rest

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/views.py
> +    #logout(request)
remove

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/views.py
> +            template = loader.get_template("taform/confirmation.html")
switch to single quotes like the rest to be consistent

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/views.py
> +     #%s"%download_name
remove

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/views.py
> +    filename     = "../../static/taform/course_template.csv" # Select your file here.
remove spaces for all the equal signs

2017-07-11 05:05 UTC, j2kan commented on taworks/taform/templates/taform/test.html
> +{% if user.is_authenticated %}
Please rename this file to something like sucess.html

2017-07-11 13:09 UTC, lauradobson commented on taworks/taform/urls.py
> +    url(r'application.html', views.apply, name='application'),
explain?

2017-07-11 18:49 UTC, lauradobson commented on taworks/taform/templates/taform/course_list.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
it's already in there?

2017-07-11 18:50 UTC, lauradobson commented on taworks/taform/templates/taform/course_list.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
it's already in there?

2017-07-11 22:26 UTC, j2kan requested changes

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +            <button class="btn-lg btn-success" formaction="{% url 'home' %}" style="vertical-align:top; float: right">Home</button>
I saw  <form> tags and didn't see {% csrf_token %}
you should remove the  <form> tags that isn't being used all together.

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/static/taform/css/style.css
>  .tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;border-to
can you make the style sheet follow the same style.

i.e.

.someDiv {
  background: red;
  padding: 2em;
  border: 1px solid black;
}

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +{% load staticfiles %}
this should be changed to load static

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +<font color="red">{{error}}</font>
can you add to style.css for color="red"? I can see it being used in other places as well for other pages.

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +<form>
indent the block after {% if user.is_authenticated %}

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/course_success.html
> +<a href="{% url 'login' %}">login</a>
indent this line

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +{% csrf_token %}
this should only be used inside form ?

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +    <button class="button" formaction="{% url 'home' %}">Home</button>
Is this button for logout?

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
>  def course_list(request):
Do we need @login_required here?

https://docs.djangoproject.com/en/1.11/topics/auth/default/

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +{% if user.is_authenticated %}
Can you do the user.is_authenticated check as part of views.py?

for example:
def home(request):
    if not request.user.is_authenticated:
        return render(request, 'myapp/login_error.html')
    else:
        return render(request, 'taform/home.html')

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +        <button class="button" formaction="{% url 'logout' %}">Logout</button>
does it work with csrf_token added here?

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/urls.py
> +    url(r'application.html', views.apply, name='application'),
not sure what that was, was pretty late when i reviewed

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
> +def validate_temp():
very nice udf for validating.

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
> +    return True
If there was an issue inserting into TempCourse table, this function will return True.
I think the function should return False if there was nothing to validate in the first place.

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
> +        if is_valid == True:
nit.
you can just have if is_valid:

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
> +            template = loader.get_template('taform/confirmation.html')
what does template do here?

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
> +def send_file(request):
Can you move this above your UDFS?

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
>      if 'Submit' in request.POST:
Does the submit and cancel button only show up after csv upload?

2017-07-11 22:26 UTC, j2kan commented on taworks/taform/views.py
> +    import os, tempfile, zipfile
move these import statements to the top of this file.

2017-07-11 23:13 UTC, lauradobson commented on taworks/taform/templates/taform/course_list.html
> +    <button class="button" formaction="{% url 'home' %}">Home</button>
Nope, its to return back to the home page from the Upload Courses page

2017-07-11 23:14 UTC, lauradobson commented on taworks/taform/templates/taform/course_success.html
> +<form>
Sighhh you told me this didn't need to be indented so I removed it

2017-07-11 23:14 UTC, lauradobson commented on taworks/taform/templates/taform/course_success.html
> +<form>
Will add back

2017-07-11 23:14 UTC, lauradobson commented on taworks/taform/templates/taform/home.html
> +{% if user.is_authenticated %}
I can try but imagine this as php sessions.

2017-07-11 23:15 UTC, lauradobson commented on taworks/taform/views.py
>      if 'Submit' in request.POST:
yep..... it's on the confirmation page.

2017-07-11 23:16 UTC, lauradobson commented on taworks/taform/views.py
> +    return True
I don't understand how that will make a difference. Regardless, the form is being validated

2017-07-12 00:52 UTC, lauradobson commented on taworks/taform/views.py
>  def course_list(request):
no it's working w/o it

2017-07-12 01:10 UTC, lauradobson commented on taworks/taform/views.py
> +    import os, tempfile, zipfile
from django.core.servers.basehttp import FileWrapper needs to be inside the function or else it throws and error

2017-07-12 02:18 UTC, j2kan requested changes

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/static/taform/css/style.css
> +    color: #FE0909;
lots of white space showing up in the git hub review

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/static/taform/css/style.css
> +table {
remove?

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/static/taform/css/style.css
> +}
looking really good!!!

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/templates/taform/confirmation.html
> +<p>You would like to upload the following data. Is this correct? If yes, select "Commit". If no, select "Don't Commit".
ending </p>?

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/templates/taform/confirmation.html
> +<p>You would like to upload the following data. Is this correct? If yes, select "Commit". If no, select "Don't Commit".
uhh it skipped it ending paragraph tag

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/templates/taform/confirmation.html
> +<div id="font">Please note: Submitting this data will reset the database for the upcoming term and all existing applications will be deleted. </div>
to be consistent
div
     text
div

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/templates/taform/course_list.html
> +<p>Please ensure the file you upload is in CSV format. This file must contain the course ID, name, instructor and email information. Click <a href="../../static/taform/course_template.csv" download="
ending p tag?
also i think with p tag you can just press enter and have this over multiple lines right?

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/templates/taform/course_success.html
> +{% csrf_token %}
this should be after the form tag

2017-07-12 02:18 UTC, j2kan commented on taworks/taform/templates/taform/home.html
> +
remove extra line

2017-07-12 02:21 UTC, lauradobson commented on taworks/taform/templates/taform/confirmation.html
> +<div id="font">Please note: Submitting this data will reset the database for the upcoming term and all existing applications will be deleted. </div>
ill just take the heading out of a div...

2017-07-12 02:23 UTC, lauradobson commented on taworks/taform/static/taform/css/style.css
> +table {
nope this is needed for the rest of the custom css tags

2017-07-12 02:24 UTC, lauradobson commented on taworks/taform/static/taform/css/style.css
> +    color: #FE0909;
not sure why..isn't this way in sublime (did the tab thing to make sure)

2017-07-12 02:45 UTC, j2kan commented on taworks/taform/static/taform/css/style.css
> +table {
ok

2017-07-12 02:45 UTC, j2kan commented on taworks/taform/static/taform/css/style.css
> +    color: #FE0909;
yeah looks good now

2017-07-12 02:45 UTC, j2kan commented on taworks/taform/templates/taform/confirmation.html
> +
remove extra line

2017-07-12 02:46 UTC, j2kan commented on taworks/taform/templates/taform/course_success.html
> +	{% csrf_token %}
seems too indented

2017-07-12 02:48 UTC, j2kan approved these changes

2017-07-12 02:48 UTC, j2kan commented
👍

2017-07-12 03:02 UTC, merged