Adding functionality for visa expiry date to only show when citizensh…
j2kan/ta-works pull request #20
Opened 2018-01-19 20:25 UTC by amyleblond

changed: 

- html tags <label> and <td> are used to store event handlers and hidden option
- model for student_visa_expiry_date help text is changed to remove "only fill in when..." to "form must be yyyy-mm-dd"
- tested on safari and chrome
- tested for saving application to db on local - student visa and non student visa

2018-01-20 22:52 UTC, smwatts reviewed
Looks good to me

2018-01-21 17:14 UTC, j2kan commented on taworks/taform/static/taform/js/app.js
> +	var strvisaSelect = visaSelect.options[visaSelect.selectedIndex].text;
can you make this strVisaSelect?

2018-01-21 17:15 UTC, j2kan requested changes
just 1 naming otherwise lgtm to merge.

2018-01-21 18:42 UTC, amyleblond commented
updated var name to strVisaSelect!

2018-01-21 19:56 UTC, j2kan approved these changes

2018-01-24 02:55 UTC, merged