added functionality for additional instructions before adding courses…
j2kan/ta-works pull request #60
Opened 2018-02-18 21:18 UTC by lauradobson

… and submitting ta application

2018-02-19 14:22 UTC, amyleblond submitted a review, later dismissed
"final confirmation" - thumbs up :)

2018-02-19 19:48 UTC, j2kan reviewed
@lauradobson 
The following task was also on the ticket:
 - Application Page - Add what the reason for applying to each course should contain

2018-02-19 19:48 UTC, j2kan commented on taworks/taform/templates/taform/application.html
> +<input type="button" id ="btn" value="Submit" disabled>
remove this if we aren't using it

I think we should also rename it from btn -> application-btn

2018-02-19 19:56 UTC, j2kan commented
@lauradobson @amyleblond 
if i press submit, then cancel then submit then submit the page just refreshes.

2018-02-20 14:42 UTC, lauradobson commented
I wasn't able to replicate your submit, then cancel then submit submit error. @amyleblond  can you give it a try when you have a chance?

2018-02-20 14:44 UTC, lauradobson commented
@j2kan if this happend when you had empty fields or error checks failed, the page will go back to the TA form and you will see error messages such as (which to my understanding is how the system should act):

![image](https://user-images.githubusercontent.com/22123056/36430210-985bc9de-1622-11e8-8c05-2eb3d4465470.png)


Can you try this again with all the fields properly filled out and let me know if you get the same error? :)

2018-02-20 14:44 UTC, j2kan commented
@lauradobson fyi: i was using chrome.

2018-02-20 14:45 UTC, lauradobson commented
@j2kan I'm using chrome too

2018-02-20 14:46 UTC, j2kan commented
@lauradobson @amyleblond  
sorry i'll be more clear with my steps.
1. fill out the whole form including preferences
2. check all the boxes
3. press submit
4. press cancel or escape when confirmation box shows up
5. press submit
6 press submit on confirmation box
result: the page refreshes for me and the form doesn't submit

2018-02-20 15:23 UTC, j2kan requested changes
1. remove extra button line
2. add reason instructions

2018-02-20 17:39 UTC, amyleblond commented
I had to run on Safari because my chrome isn't updating -- but I got the same issue as @j2kan 

1. fill out application form
2. press submit -> on pop up press cancel
3. don't make any changes to the form
4. press submit -> on pop up press submit

outcome: page is refreshed, all fields are clear and it hasn't been added to db

2018-02-26 18:50 UTC, closed without merging