App cleanup
j2kan/ta-works pull request #95
Opened 2018-03-04 22:48 UTC by lauradobson

1. Added more description to the description of "Open/Closed" Status
2. Cosmetic changes on the courses table on the application page.
3. Larger/more noticeable "reason" button
4. Student ID and other errors showing up in the Basic Information table. Student form validation occurs prior to the form trying to submit.
5. Updated Application instructions directly on master.
6. ExpecTAtions dropdown created - initialized to "No".

2018-03-05 02:05 UTC, smwatts commented
@lauradobson mind merging master into your branch? I'll test it after :)

2018-03-05 03:36 UTC, amyleblond requested changes
i'm still not getting the student_id error check
![screen shot 2018-03-04 at 10 29 15 pm](https://user-images.githubusercontent.com/22120696/36956378-0dd9cb7e-1ffc-11e8-9868-c6b844ce43c7.png) - just redirects me to the page but doesnt say why

also the popup message is showing on the screen under submit before thepopup loads, not sure if this was intended--ran incognito and did all the collectstatic
![screen shot 2018-03-04 at 10 36 02 pm](https://user-images.githubusercontent.com/22120696/36956449-7268d17a-1ffc-11e8-9132-a783df937d8f.png)

2018-03-05 04:21 UTC, j2kan commented on taworks/taform/templates/taform/application.html
>          <div id="left">
can you change line 177 and line 178 to classes as well? they should have never been ids.

2018-03-05 04:21 UTC, j2kan commented on taworks/taform/views.py
> +                'form_valid' : form_valid
if form isn't valid here, does it need to go in the try statement?

2018-03-05 16:22 UTC, amyleblond approved these changes

2018-03-05 20:23 UTC, j2kan commented on taworks/taform/views.py
> +                form_valid = True
wouldn't the form also not be valid if it's in the else statement?

2018-03-06 00:12 UTC, j2kan commented
form_valid seems to always be false now?

2018-03-06 04:19 UTC, smwatts commented
Mind merging master again? sorry we're developing too fast for what we're reviewing lol. Just think a few of my comments will be based on things fixed in earlier merged PRs.

Let me know if thats the case for these comments:

Can this text go above the submit button?
![screen shot 2018-03-05 at 11 16 59 pm](https://user-images.githubusercontent.com/22134649/37013979-7352596a-20cb-11e8-9ddb-796c64b35bd8.png)

This damn asterisk lol, should be removed after the citizenship selection:
![screen shot 2018-03-05 at 11 14 58 pm](https://user-images.githubusercontent.com/22134649/37014017-a9704b42-20cb-11e8-9105-1c620c88997b.png)

2018-03-06 05:16 UTC, j2kan commented
does enter reason button still disappear?

2018-03-06 05:24 UTC, j2kan requested changes
form_valid is always false. what's the intention with it?

2018-03-06 16:48 UTC, amyleblond commented on taworks/taform/templates/taform/application.html
> +<div class="divWordWrap">
can we make this word wrap longer? confirmation looks weird
![screen shot 2018-03-06 at 11 43 17 am](https://user-images.githubusercontent.com/22120696/37045536-24f0fdd0-2134-11e8-97b7-114fb0b52083.png)

2018-03-07 03:53 UTC, closed without merging